### ISSUE TITLE
Evaluate options for hosting tutorials:

### ISSUE THREAD

**Issue by traek** [traek/copacodersclub#3]
- [x] Hard-coded HTML (pros: learning opportunity)
- [x] Pico CMS (pro: native markdown support; no SQL)
- [x] Open source LMS
- [x] Third party sites

**Comment by traek** [comment]
@nemathew what do you think is the best way to deliver these tutorials to the students? I've looked into LMS solutions before but they can be quite complex. The content you're putting together in md could easily be hosted by something like [Pico CMS](http://picocms.org/) and could be hosted on our website easily but it wouldn't have nice things like logging in and tracking of their progress (not sure that's needed anyway). Now that I think about it, what would you think about just hosting the markdown for now on github pages? It would mean tutorials would go in to another repository.

**Comment by nemathew** [comment]
I like the idea of GitHub pages, that way any code that we give them could be easily found in the same system and we don't have to worry about hosting more files than needed on the website server.

**Comment by traek** [comment]
Okay, so I enabled Github Pages, which should do the trick. Unfortunately, it's not super straight-forward to migrate the files to the new branch without doing a full commit. Given it's your code, I thought it would be appropriate for you to just copy the files into [gh-pages](/copacoders/copacoders/tree/gh-pages) so it continues to show your work and then we can remove it from the [master branch](/copacoders/copacoders).

I think we can close this issue.
